name: ci

on:
  push:
    branches:
      - 'bionic'
  pull_request:
    branches:
      - 'bionic'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platforms: [amd64]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.platforms }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.${{ matrix.platforms }}
          platforms: linux/${{ matrix.platforms }}
          push: true
          tags: |
            skb666/ubuntu-desktop-lxde-vnc:latest
            skb666/ubuntu-desktop-lxde-vnc:bionic
